/*
 * Copyright (C) 2026 Bohemian Miser <https://substack.com/@bohemianmiser>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * Attribution for a forged icon (issue #283).
 *
 * An icon is generated by a Cloud Task, which runs with no request context and
 * therefore cannot call `verifyAuth()`. The only identity available at forge
 * time is the owner of the recipe(s) whose nodes queued the ingredient, so that
 * is what "creator" means here: the owner of the recipe that triggered the
 * forge.
 *
 * Anonymous recipes carry no `ownerId`, so they contribute nothing and the icon
 * is simply left unattributed rather than attributed to a placeholder.
 *
 * UID-only by design — no display names or emails, matching the `icon_forged`
 * log signal (see docs/alerting-icon-forge.md).
 */

/** The subset of a recipe document this module reads. */
export interface RecipeOwnerSource {
    ownerId?: unknown;
}

/**
 * Deduplicated owner UIDs for the recipes that triggered a forge, in first-seen
 * order. Missing docs, anonymous recipes and non-string `ownerId`s are dropped.
 */
export function deriveIconOwners(recipes: Array<RecipeOwnerSource | undefined | null>): string[] {
    const owners: string[] = [];
    for (const recipe of recipes ?? []) {
        const ownerId = recipe?.ownerId;
        if (typeof ownerId !== 'string') continue;
        const trimmed = ownerId.trim();
        if (!trimmed || owners.includes(trimmed)) continue;
        owners.push(trimmed);
    }
    return owners;
}

/**
 * The single UID stored as the icon's creator.
 *
 * One icon can be queued by several recipes at once, so this picks the first
 * owner in queue order — the recipe that opened the queue entry, i.e. whoever
 * actually caused the icon to exist. Returns undefined when nothing is
 * attributable, so callers can omit the field entirely instead of writing null.
 */
export function pickIconCreator(owners: string[]): string | undefined {
    return owners.find(o => typeof o === 'string' && o.length > 0);
}
