import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Recipe RPG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`antialiased bg-zinc-900 text-white`}
      >
        {children}
      </body>
    </html>
  );
}